# Book settings
title: Interactive-Charts
author: Grant M. Seiter
copyright : "2021"
logo: logo.png

repository:
  url: https://github.com/grantseiter/Interactive-Charts
  path_to_book: docs
  branch: main

html:
  home_page_in_navbar : false
  use_edit_page_button: false
  use_issues_button: false
  use_repository_button: true
